version: "3.3"

services:
  is_core:
    build: 
      context: ./build
    container_name: "is-core"
    volumes: 
      - ./build/deployments/:/opt/server/wildfly/standalone/deployments/
    depends_on:
      - is_mysql_db
    restart: always
    ports:
      - 8445:8443
      - 8883:8080
      - 9992:9990
    networks:
      - NETWORK

  is_mysql_db:
    container_name: "is-db"
    image: "mysql:latest"
    restart: always
    environment:
      - MYSQL_DATABASE=invoices
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql-data/init/:/docker-entrypoint-initdb.d/ # init database
      - ./mysql-data/data/:/var/lib/mysql/              # data storage
    ports:
      - "3306:3306"
    networks:
      - NETWORK
  
  is_keycloak:
    image: jboss/keycloak:12.0.4
    container_name: "is-keycloak"
    restart: always
    volumes:
      - ./keycloak-imports:/opt/jboss/keycloak/imports
    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled          
      DB_VENDOR: h2
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8444:8443
      - 8081:8080
      - 9991:9990
    networks:
      - NETWORK

  is_nginx:
    image: nginx:latest
    container_name: is-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      #nginx and default servers
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./build/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      #copy build files from dist folders
      - ./build/nginx/dist/invoicing-systems:/usr/share/nginx/invoicing-systems/html
    
networks:
  NETWORK: